name: Build PDF

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: moss/xelatex:1.3.3
      volumes:
        - .:/data
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6

      - name: Clean artifacts, if any
        run: make clean

      - name: Compile PDF
        run: make pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v6
        with:
          name: main
          path: "report/*.pdf"
          if-no-files-found: error
          retention-days: 30